### ISSUE TITLE
TypeError: cafile, capath and cadata cannot be all omitted (Python 2.7.10 and CentOS 6.7)

### ISSUE THREAD

**Issue by irr** [datacenter/acitoolkit#127]
Hi,

I was testing my system using a new environment (CentOS 6.7 and Python 2.7.10) and when I tried to connect on APIC I am receiving the following error:

```python
session = Session("https://apic", APIC_USER, APIC_PWD)
session.login()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/irocha/dev/lib/python2.7/site-packages/acitoolkit-0.3.1-py2.7.egg/acitoolkit/acisession.py", line 480, in login
  File "/home/irocha/dev/lib/python2.7/site-packages/acitoolkit-0.3.1-py2.7.egg/acitoolkit/acisession.py", line 465, in _send_login
  File "/home/irocha/dev/lib/python2.7/site-packages/acitoolkit-0.3.1-py2.7.egg/acitoolkit/acisession.py", line 249, in _open_web_socket
  File "/home/irocha/dev/lib/python2.7/site-packages/websocket_client-0.32.0-py2.7.egg/websocket/_core.py", line 104, in create_connection
  File "/home/irocha/dev/lib/python2.7/site-packages/websocket_client-0.32.0-py2.7.egg/websocket/_core.py", line 266, in connect
  File "/home/irocha/dev/lib/python2.7/site-packages/websocket_client-0.32.0-py2.7.egg/websocket/_http.py", line 69, in connect
  File "/home/irocha/dev/lib/python2.7/site-packages/websocket_client-0.32.0-py2.7.egg/websocket/_http.py", line 154, in _ssl_socket
  File "/home/irocha/dev/lib/python2.7/site-packages/websocket_client-0.32.0-py2.7.egg/websocket/_http.py", line 128, in _wrap_sni_socket
TypeError: cafile, capath and cadata cannot be all omitted
```

I tested with Cobra SDK and everything worked:
```python
session = LoginSession('https://apic', APIC_USER, APIC_PWD)
moDir = MoDirectory(session)
moDir.login()
nsCfg = ConfigRequest()
...
```
My new environment is:
```shell
$ uname -a
Linux irrlab 2.6.32-573.3.1.el6.x86_64 #1 SMP Thu Aug 13 22:55:16 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
```shell
$ rpm -qa|grep ssl
openssl-devel-1.0.1e-42.el6.x86_64
openssl-1.0.1e-42.el6.x86_64
```
```shell
$ pip freeze|grep -i aci
acicobra===1.1-1r
acimodel===1.1-1r
acitoolkit==0.3.1
```

Do I need to change something on CentOS 6.7? Any help?

Regards,
Ivan

**Comment by irr** [comment]
Note (caveat): If I disable subscription **(subscription_enabled=False)**, everything works (I don't know about side effects)

```python
session = Session("https://apic", APIC_USER, APIC_PWD, 
                  verify_ssl=False, subscription_enabled=False)
```

**Comment by michsmit99** [comment]
Hi Ivan, thanks for the detailed description, this really helps narrow it down. The subscription_enabled is strictly for the websocket event communication.  If you are using the toolkit for configuration only, this is not needed.  It is only needed for  subscribe/get_event calls. It looks like this is failing in the websocket connection. I have not been able to reproduce this yet. I upgraded my CentOS 6.3 setup to python2.7 (was 2.6) and I'm not seeing the problem. I will switch to CentOS 6.7 and continue debugging. Thanks, Michael

**Comment by daconex** [comment]
Can confirm that `TypeError: cafile, capath and cadata cannot be all omitted` is an issue with websocket-client (https://github.com/liris/websocket-client). Toward the bottom of the page there is a section about disabling hostname verification and ssl cert verification. Unfortunately, `sslopt={"check_hostname": False}` doesn't fix the issue.

cc @liris
