### ISSUE TITLE
aci-diagram failing due to ValueError

### ISSUE THREAD

**Issue by mujeesh** [datacenter/acitoolkit#170]
Thanks for looking at my issue.

I am not able to login to APIC properly using session 

I have tried to run the application by calling diagram.py by like this 

 python .\diagram.py -u "https://10.66.80.162" -l "admin" -p "admincisco" -t "tn-aobst" -o "C:/Users/MUSHAMSU/Desktop/ACI"

Debugging
-------------
ipdb> session.login()
ERROR:root:Unable to open websocket connection due to WebSocketE
*** RuntimeError: cannot set daemon status of active thread
ipdb>
__________________________________________________

and I am not getting any Tenants details from Tenant.get_deep(session, args.tenants)

c:\users\mushamsu\desktop\aci\toolkit\acitoolkit\applications\aci-diagram\diagram.py(37)<module>()
     36 if args.tenants:
---> 37     tenants = Tenant.get_deep(session, args.tenants)
     38 else:

ipdb> n
> c:\users\mushamsu\desktop\aci\toolkit\acitoolkit\applications\aci-diagram\diagram.py(42)<module>()
     41
---> 42 def tn_node(tn):
     43     return "cluster-tn-" + tn.name

ipdb> tenants
[ ]

Could You Please help me on this.

Cheers,
Mujeesh

**Comment by cgascoig** [comment]
Hi Mujeesh,

The issue title says you were getting a ValueError - could you post the traceback for that?

I think "RuntimeError: cannot set daemon status of active thread" is due to session.login() being called twice during your debugging session.

Thanks,
Chris

**Comment by mujeesh** [comment]
Chris,

Drawing graph to C:/Users/MUSHAMSU/Desktop/ACI
Traceback (most recent call last):
  File "diagram.py", line 135, in <module>
    graph.draw(args.output, prog='dot')
  File "C:\Python27\lib\site-packages\pygraphviz\agraph.py", line 1474, in draw
    data = self._run_prog(prog, args)
  File "C:\Python27\lib\site-packages\pygraphviz\agraph.py", line 1308, in _run_prog
    runprog = r'"%s"' % self._get_prog(prog)
  File "C:\Python27\lib\site-packages\pygraphviz\agraph.py", line 1295, in _get_prog
    raise ValueError("Program %s not found in path." % prog)
ValueError: Program dot not found in path.

**Comment by mujeesh** [comment]
Chris ,

I am able to run the program in my ubuntu virtual box ,

But the image have some problem.I have attached the image.
![test](https://cloud.githubusercontent.com/assets/5373029/13852649/0c317d42-ec89-11e5-8044-3afc7d0e6860.jpg)

something wrong when I am running in windows

Traceback (most recent call last):
  File "diagram.py", line 38, in <module>
    tenants = Tenant.get_deep(session, args.tenants)
  File "build\bdist.win32\egg\acitoolkit\acitoolkit.py", line 210, in get_deep
  File "build\bdist.win32\egg\acitoolkit\acibaseobject.py", line 396, in get_deep
  File "build\bdist.win32\egg\acitoolkit\acibaseobject.py", line 396, in get_deep
  File "build\bdist.win32\egg\acitoolkit\acibaseobject.py", line 396, in get_deep
  File "build\bdist.win32\egg\acitoolkit\acitoolkit.py", line 3957, in get_deep
  File "build\bdist.win32\egg\acitoolkit\acitoolkit.py", line 3920, in _populate_interface_info
AttributeError: 'NoneType' object has no attribute 'group'
