### ISSUE TITLE
Impport error from aciConSearch.py

### ISSUE THREAD

**Issue by mujeesh** [datacenter/acitoolkit#171]
Hello All ,
i am getting import error from connection_search application.

Traceback (most recent call last):
  File "aciConSearch.py", line 35, in <module>
    from acitoolkit import Endpoint, Tenant, AppProfile, Contract, EPG, OutsideL3, OutsideEPG, ContractSubject, \
ImportError: cannot import name ContractSubject

Can anyone update acitoolkit

Thanks,
Mujeesh

**Comment by michsmit99** [comment]
Hi Mujeesh,
I just pulled a new clone and wasn't able to reproduce this. Is it possible that you didn't re-run "sudo python setup.py install" or "sudo python setup.py develop" ?  If the library changes, it is necessary to re-run the install after a git pull.

**Comment by mujeesh** [comment]
Thanks ..
I followed Your comment and now I am not getting the import error ,but getting WebSocketException

ERROR:root:Unable to open websocket connection due to WebSocketException
Traceback (most recent call last):
  File "aciConSearch.py", line 1270, in <module>
    main()
  File "aciConSearch.py", line 1262, in main
    sdb.build()
  File "aciConSearch.py", line 876, in build
    tenants = Tenant.get_deep(self.session)
  File "/usr/local/lib/python2.7/dist-packages/acitoolkit-0.3.1-py2.7.egg/acitoolkit/acitoolkit.py", line 210, in get_deep
    config_only=config_only)
  File "/usr/local/lib/python2.7/dist-packages/acitoolkit-0.3.1-py2.7.egg/acitoolkit/acibaseobject.py", line 396, in get_deep
    config_only=config_only)
  File "/usr/local/lib/python2.7/dist-packages/acitoolkit-0.3.1-py2.7.egg/acitoolkit/acibaseobject.py", line 396, in get_deep
    config_only=config_only)
  File "/usr/local/lib/python2.7/dist-packages/acitoolkit-0.3.1-py2.7.egg/acitoolkit/acibaseobject.py", line 396, in get_deep
    config_only=config_only)
  File "/usr/local/lib/python2.7/dist-packages/acitoolkit-0.3.1-py2.7.egg/acitoolkit/acitoolkit.py", line 3998, in get_deep
    obj._populate_interface_info(working_data)
  File "/usr/local/lib/python2.7/dist-packages/acitoolkit-0.3.1-py2.7.egg/acitoolkit/acitoolkit.py", line 3961, in _populate_interface_info
    port = re.search(r'pathep-\[eth(.+)\]$', if_dn).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
mujeesh@mujeesh-VirtualBox:~/ACI_Setup/acitoolkit/applications/connection_search$ 


Could You please guide me on this

**Comment by michsmit99** [comment]
I found a similar problem described in this thread:
https://communities.cisco.com/thread/48452?start=0&tstart=0
