### ISSUE TITLE
Unable to connect the APIC

### ISSUE THREAD

**Issue by nick00783** [datacenter/acitoolkit#198]
hello guys:
       I have a issue that I can't connect my APIC through acitoolkit now,but I have succeeded before when the APIC version is 1.1.After upgrading to the version 1.4(f),I can't connect the APIC anymore. The network is fine,I can access the APIC using chrome,is there anything to do with the version of APIC? thanks for your helping..

Here is the complete traceback:
===============================================================
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 4.5.3\helpers\pydev\pydevd.py", line 2358, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\JetBrains\PyCharm 4.5.3\helpers\pydev\pydevd.py", line 1778, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/acitoolkit-master/samples/tutorial.py", line 81, in <module>
    Login=session.login()
  File "C:\Python27\lib\site-packages\acitoolkit\acisession.py", line 404, in login
    resp = self._send_login(timeout)
  File "C:\Python27\lib\site-packages\acitoolkit\acisession.py", line 388, in _send_login
    self.subscription_thread._open_web_socket('https://' in self.api)
  File "C:\Python27\lib\site-packages\acitoolkit\acisession.py", line 188, in _open_web_socket
    self._ws = create_connection(self._ws_url, sslopt=sslopt, **kwargs)
  File "C:\Python27\lib\site-packages\websocket\_core.py", line 489, in create_connection
    websock.connect(url, **options)
  File "C:\Python27\lib\site-packages\websocket\_core.py", line 216, in connect
    options.pop('socket', None))
  File "C:\Python27\lib\site-packages\websocket\_http.py", line 73, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "C:\Python27\lib\site-packages\websocket\_http.py", line 172, in _ssl_socket
    sock = ssl.wrap_socket(sock, **sslopt)
  File "C:\Python27\lib\ssl.py", line 342, in wrap_socket
    ciphers=ciphers)
  File "C:\Python27\lib\ssl.py", line 121, in __init__
    self.do_handshake()
  File "C:\Python27\lib\ssl.py", line 281, in do_handshake
    self._sslobj.do_handshake()
socket.error: [Errno 10054] 
========================================================================

**Comment by michsmit99** [comment]
I'm not aware of any APIC version issues, but it looks like your errors are in the SSL libraries. Many operating systems come with very old python SSL libraries that require updating.  Are you able to access the APIC via http ? Also, what OS are you using ?

**Comment by nick00783** [comment]
Yes,Im able to access the APIC via https,and the OS is Windows 2008 R2 server .

**Comment by michsmit99** [comment]
When you say that you are able to access the APIC via https, is that through the browser or using the script ?  Will the script work using http (not https) ?

**Comment by nick00783** [comment]
Thanks for your helping..Problem is solved, I just reinstall everything(python,openssh,acitoolkit),then no more Error..
