### ISSUE TITLE
Namespace' object has no attribute 'interface' (aci-show-interface-stats.py)

### ISSUE THREAD

**Issue by ahmedaljawad** [datacenter/acitoolkit#210]
HI all 
  Im new to the ACI programming . im getting the error below when I run aci-show-interface-stats.py

:\Python27\python.exe C:/Python27/Lib/site-packages/acitoolkit/datacenter-acitoolkit-v0.3.2-489-g43c3a47/datacenter-acitoolkit-43c3a47/samples/aci-show-interface-stats.py
Traceback (most recent call last):
  File "C:/Python27/Lib/site-packages/acitoolkit/datacenter-acitoolkit-v0.3.2-489-g43c3a47/datacenter-acitoolkit-43c3a47/samples/aci-show-interface-stats.py", line 147, in <module>
    main()
  File "C:/Python27/Lib/site-packages/acitoolkit/datacenter-acitoolkit-v0.3.2-489-g43c3a47/datacenter-acitoolkit-43c3a47/samples/aci-show-interface-stats.py", line 131, in main
    if args.interface:
AttributeError: 'Namespace' object has no attribute 'interface'  

Thank you

**Comment by michsmit99** [comment]
Seems to work on my system. Do other samples work ? Have you run the 'python setup.py install' ?

**Comment by ahmedaljawad** [comment]
I run the  tutorial code and it worked just fine .
