### ISSUE TITLE
Tenant.get_deep() gets traceback after I add static VPC binding to an EPG

### ISSUE THREAD

**Issue by krruther** [datacenter/acitoolkit#280]
I am having an issue with the Tenant.get_deep() method.  I've included a code snippet below which prints out the json representation of a tenant.   It works fine.  After I add a VPC static binding to an EPG in the tenant - I get a traceback and an assertion error.    Prior to adding the VPC static binding or if I just add a port binding to the tenant - this does not happen.  
Here's the code snippet:
import acitoolkit.acitoolkit as aci
session = aci.Session('https://10.x.x.x', 'xxxxx', 'xxxxx')
resp=session.login()
print resp
<Response [200]>
tenant = aci.Tenant.get_deep(session, names=['xxxlab'])
print tenant[0].get_json()

Here's the traceback:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/acitoolkit/acitoolkit.py", line 100, in get_json
    attributes=attr)
  File "/usr/lib/python2.7/site-packages/acitoolkit/acibaseobject.py", line 996, in get_json
    data = child.get_json()
  File "/usr/lib/python2.7/site-packages/acitoolkit/acitoolkit.py", line 334, in get_json
    attributes=attr)
  File "/usr/lib/python2.7/site-packages/acitoolkit/acibaseobject.py", line 996, in get_json
    data = child.get_json()
  File "/usr/lib/python2.7/site-packages/acitoolkit/acitoolkit.py", line 1276, in get_json
    'tDn': interface._get_path()}}}
  File "/usr/lib/python2.7/site-packages/acitoolkit/acitoolkit.py", line 436, in _get_path
    return relation.item._get_path()
  File "/usr/lib/python2.7/site-packages/acitoolkit/acitoolkit.py", line 4768, in _get_path
    assert len(self._interfaces)
AssertionError

**Comment by michsmit99** [comment]
I just submitted a fix (commit 3ce5b08742196a51594b63a26cc4c1cdbcf46e00) that should address this.

**Comment by krruther** [comment]
That fixed the issue I was having.  Thank you for the fast response.
