### ISSUE TITLE
global name 'InsecureRequestWarning' is not defined [QUESTION]

### ISSUE THREAD

**Issue by pax80** [datacenter/acitoolkit#284]
when i clone the repo on my local machine and i test some example i get the 
**global name 'InsecureRequestWarning' is not defined**

this is not happening when i power up a new machine via vagrant file.

is this a known issue? am i missing something on the 

`vagrant@processing:/vagrant/test_aci/acitoolkit$ python samples/aci-show-nodes.py
APIC login username: ******
APIC URL: *****
APIC Password:
Traceback (most recent call last):
  File "samples/aci-show-nodes.py", line 76, in <module>
    main()
  File "samples/aci-show-nodes.py", line 56, in main
    resp = session.login()
  File "/vagrant/test_aci/acitoolkit/acitoolkit/acisession.py", line 655, in login
    resp = self._send_login(timeout)
  File "/vagrant/test_aci/acitoolkit/acitoolkit/acisession.py", line 611, in _send_login
    requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
NameError: global name 'InsecureRequestWarning' is not defined`

Same code on the VM build on vagrant is working

KR| pax80

**Comment by michsmit99** [comment]
I've checked in a fix that should address this.  Which OS are you seeing this ?

**Comment by pax80** [comment]
on my VM it is Debian 8 running.

KR| pax80
