### ISSUE TITLE
acisession login error handling

### ISSUE THREAD

**Issue by jeremyrichardmann** [datacenter/acitoolkit#319]
When logging in with an invalid password, the acisession login routine doesn't handle the exception gracefully.

An error is logged, however an attempt is made to start the login thread daemon which errors out and a response object is never returned to the user.

Seems like returning from the caught ConnectionError exception would stop this.

Here is the error returned:

t = s.login()
ERROR:root:Could not relogin to APIC. Aborting login thread.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "acisession.py", line 675, in login
    self.login_thread.daemon = True
  File "\Python36\lib\threading.py", line 1141, in daemon
    raise RuntimeError("cannot set daemon status of active thread")
RuntimeError: cannot set daemon status of active thread

**Comment by jeremyrichardmann** [comment]
Looks like this was fixed with the most recent commit.
