### ISSUE TITLE
Running acitoolkit on Ubuntu VM, but error when login APIC.

### ISSUE THREAD

**Issue by itbj** [datacenter/acitoolkit#32]
I tested the acitoolkitcli.py, can not run ok. I got the error message

  File "./acitoolkitcli.py", line 1293, in <module>
    apic.login()
  File "build/bdist.linux-x86_64/egg/acitoolkit/acisession.py", line 232, in login

The OS is:Linux aci-virtual-machine 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by davivcgarcia** [comment]
Looks like the message error is truncated. Are you sure there is no exception description in the error message?

**Comment by itbj** [comment]
root@aci-virtual-machine:/home/aci/app# ./aci06.py
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "./aci06.py", line 25, in <module>
    session.login()
  File "build/bdist.linux-x86_64/egg/acitoolkit/acisession.py", line 232, in login
  File "build/bdist.linux-x86_64/egg/acitoolkit/acisession.py", line 216, in _send_login
  File "build/bdist.linux-x86_64/egg/acitoolkit/acisession.py", line 104, in _open_web_socket
  File "/usr/local/lib/python2.7/dist-packages/websocket_client-0.3-py2.7.egg/websocket.py", line 70, in create_connection
  File "/usr/local/lib/python2.7/dist-packages/websocket_client-0.3-py2.7.egg/websocket.py", line 139, in connect
  File "/usr/local/lib/python2.7/dist-packages/websocket_client-0.3-py2.7.egg/websocket.py", line 48, in _parse_url
ValueError: scheme wss is not supported

**Comment by itbj** [comment]
Same error like this:
root@aci-virtual-machine:/home/aci/app# python tutorial.py
----------------------------------
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "tutorial.py", line 57, in <module>
    session.login()
  File "build/bdist.linux-x86_64/egg/acitoolkit/acisession.py", line 232, in login
  File "build/bdist.linux-x86_64/egg/acitoolkit/acisession.py", line 216, in _send_login
  File "build/bdist.linux-x86_64/egg/acitoolkit/acisession.py", line 104, in _open_web_socket
  File "/usr/local/lib/python2.7/dist-packages/websocket_client-0.3-py2.7.egg/websocket.py", line 70, in create_connection
  File "/usr/local/lib/python2.7/dist-packages/websocket_client-0.3-py2.7.egg/websocket.py", line 139, in connect
  File "/usr/local/lib/python2.7/dist-packages/websocket_client-0.3-py2.7.egg/websocket.py", line 48, in _parse_url
ValueError: scheme wss is not supported
root@aci-virtual-machine:/home/aci/app#

**Comment by pjferrell** [comment]
You're using an old release of the websocket-client package that didn't support wss scheme.  Try upgrading that package.

**Comment by mtimm** [comment]
wss scheme has been supported in the websocket-client since v0.4.0 which came out in 2011.  If this requirement exists - which it obviously does, the dependency on websocket-client should specify a >= version in the setup.py or a requirements file.

**Comment by itbj** [comment]
$ sudo python setup.py install
Installed /usr/local/lib/python2.7/dist-packages/acitoolkit-0.1-py2.7.egg
Processing dependencies for acitoolkit==0.1
Searching for websocket-client==0.3
Best match: websocket-client 0.3
Processing websocket_client-0.3-py2.7.egg
websocket-client 0.3 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/websocket_client-0.3-py2.7.egg
Searching for requests==2.5.1
Best match: requests 2.5.1
Adding requests 2.5.1 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Finished processing dependencies for acitoolkit==0.1
-----------------
The  websocket-client 0.3 is already the active version in easy-install.pth , is a version old?

**Comment by itbj** [comment]
OK. Upgrade the websocket-client to 0.23.0. the tutorials.py is ok. Thank you all very much.
