### ISSUE TITLE
AttributeError when running script

### ISSUE THREAD

**Issue by tomjohnsmith** [datacenter/acitoolkit#335]
Getting the following error when running the script:

Traceback (most recent call last):
  File "test4.py", line 40, in <module>
    main()
  File "test4.py", line 23, in main
    interfaces = ACI.Interface.get(session)
  File "/home/sutsmith/test-env/lib/python3.5/site-packages/acitoolkit/aciphysobject.py", line 3021, in get
    interface_obj = ACI._interface_from_dn(dist_name)
AttributeError: module 'acitoolkit' has no attribute '_interface_from_dn'

**Comment by sbalasa** [comment]
What's the fix ?

**Comment by jcarre59** [comment]
I got the same issue:

 File "C:\Users\jean.carre\jc_projets\APIC\venv\Lib\site-packages\acitoolkit\aciphysobject.py", line 3021, in get
interface_obj = ACI._interface_from_dn(dist_name)

Apparently the object ACI has no such attribute define in the library

**Comment by jcarre59** [comment]
workaround provided there
https://github.com/datacenter/acitoolkit/issues/356
