### ISSUE TITLE
Invalid scheme on APIC websocket refresh

### ISSUE THREAD

**Issue by sigurd120** [datacenter/acitoolkit#343]
I'm using acitoolkit to set up a Websocket subscription on the Cisco sandboxapicdc. Initially, everything works great, and I get updates when anything changes on the APIC. However, when the subscription is about to refresh (after about a minute), I get the exception below. I'm running the code in [this file on Github](https://github.com/CiscoDevNet/aci-learning-labs-code-samples/blob/master/sbx-intermediate-aci/sbx-intermediate-aci-03_websockets/acitoolkit_websocket.py). It seems as if acitoolkit attempts to open a websocket with the https prefix. 

```
Listening for Events...

WARNING:root:Websocket not established on subscription refresh. Re-establishing websocket
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/siggen/Projects/aci-learning-labs-code-samples/acitoolkit/acitoolkit/acisession.py", line 441, in run
    self.refresh_subscriptions()
  File "/home/siggen/Projects/aci-learning-labs-code-samples/acitoolkit/acitoolkit/acisession.py", line 250, in refresh_subscriptions
    self._open_web_socket('https://' in subscription)
  File "/home/siggen/Projects/aci-learning-labs-code-samples/acitoolkit/acitoolkit/acisession.py", line 288, in _open_web_socket
    self._ws = create_connection(self._ws_url, sslopt=sslopt, **kwargs)
  File "/home/siggen/Projects/aci-learning-labs-code-samples/venv/local/lib/python2.7/site-packages/websocket/_core.py", line 514, in create_connection
    websock.connect(url, **options)
  File "/home/siggen/Projects/aci-learning-labs-code-samples/venv/local/lib/python2.7/site-packages/websocket/_core.py", line 232, in connect
    options.pop('socket', None))
  File "/home/siggen/Projects/aci-learning-labs-code-samples/venv/local/lib/python2.7/site-packages/websocket/_http.py", line 107, in connect
    hostname, port, resource, is_secure = parse_url(url)
  File "/home/siggen/Projects/aci-learning-labs-code-samples/venv/local/lib/python2.7/site-packages/websocket/_url.py", line 63, in parse_url
    raise ValueError("scheme %s is invalid" % scheme)
ValueError: scheme https is invalid
```

**Comment by Bharath-MR-007** [comment]
Hello Experts,
I am getting below error while i am trying to fetch tenant health with --continuous argument.
" **_aci-show-tenant-health.py --continuous_** "

Websocket not established on subscription refresh. Re-establishing websocket
