### ISSUE TITLE
Issue in application testharness

### ISSUE THREAD

**Issue by nileshgore25** [datacenter/acitoolkit#363]
(acipy37) [root@localhost testharness]# python apic_test_harness.py --directory ../snapback/apic-config-db/
Traceback (most recent call last):
  File "apic_test_harness.py", line 161, in <module>
    session = FakeSession(filenames)
  File "/root/aciprog/aci_ansible_learning_labs_code_samples/acipy37/lib/python3.7/site-packages/acitoolkit-0.4-py3.7.egg/acitoolkit/acifakeapic.py", line 100, in __init__
  File "/root/aciprog/aci_ansible_learning_labs_code_samples/acipy37/lib/python3.7/site-packages/acitoolkit-0.4-py3.7.egg/acitoolkit/acifakeapic.py", line 288, in _fill_data
AttributeError: 'dict' object has no attribute 'iteritems'
(acipy37) [root@localhost testharness]#

**Comment by edudppaz** [comment]
This is due to iteritems being removed in Python3:

```
Remove dict.iteritems(), dict.iterkeys(), and dict.itervalues().

Instead: use dict.items(), dict.keys(), and dict.values() respectively.
```

https://wiki.python.org/moin/Python3.0#Built-In_Changes
