### ISSUE TITLE
Show endpoints sample does retrieve key error in acitoolkit.py

### ISSUE THREAD

**Issue by Nik1709** [datacenter/acitoolkit#376]
Hi there, 

I am having a problem with the "show-endpoints.py" sample. 
When I use this sample code on the Cisco ACI Always-On Sandbox I receive a keyError in acitoolkit.py

Error-message:
PS C:\Path_to_File> python .\acitoolkit_test.py
Traceback (most recent call last):
File "C:\Path_to_File\acitoolkit_test.py", line 27, in <module>
ENDPOINTS = aci.Endpoint.get(SESSION)
File "C:\Path_to_File\acitoolkit\acitoolkit.py", line 5432, in get
endpoints = Endpoint._get(session, endpoint_name, interfaces,
File "C:\Path_to_File\acitoolkit\acitoolkit.py", line 5388, in _get
endpoint.ip = str(ep['ip'])
KeyError: 'ip'

However when I try showing the tenants or the EPGs everything works just fine. 
Is this way of displaying the endpoints deprecated or am I missing something else here?

Thanks in advance!
Nik

**Comment by PratyushBasu** [comment]
Hello @Nik1709 
Could you share the output of `ep` dictionary?

Regards,
Pratyush
