### ISSUE TITLE
Python3 Issue with 'setup.py develop'

### ISSUE THREAD

**Issue by dnq** [datacenter/acitoolkit#73]
I git pulled the source code from github, then did a develop install with 'python3 setup.py develop'
Now i get the following error when i try to import the acitoolkit:

```python
→ python3
Python 3.4.3 (default, Feb 25 2015, 21:28:45)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>>from acitoolkit.acitoolkit import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/richy/Documents/3_application/python/acitoolkit/acitoolkit/__init__.py", line 13, in <module>
    from __about__ import (
ImportError: No module named '__about__'

**Comment by Edsall** [comment]
Thanks.
